-- cyberdream.nvim palette, recoloured, ported to base46
-- no pink/purple: both map to soft-gold/green
-- cyan retired to soft-gold, was last teal color

local M = {}

M.base_30 = {
  white         = "#dcdcd4",
  darker_black  = "#020202",
  black         = "#040404", -- cyberdream bg
  black2        = "#090909", -- cyberdream bg_alt
  one_bg        = "#0f0f0f",
  one_bg2       = "#141414", -- cyberdream bg_highlight
  one_bg3       = "#1a1a1a",
  grey          = "#282828",
  grey_fg       = "#4c4b3c",
  grey_fg2      = "#5c5a46",
  light_grey    = "#7b8496", -- cyberdream grey
  red           = "#ff6e5e",
  baby_pink     = "#ecd3a0",
  pink          = "#ecd3a0",
  line          = "#141414",
  green         = "#5eff6c",
  vibrant_green = "#5eff6c",
  nord_blue     = "#5ea1ff",
  blue          = "#5ea1ff",
  yellow        = "#f1ff5e",
  sun           = "#f1ff5e",
  purple        = "#b5a494",
  dark_purple   = "#b5a494",
  teal          = "#ecd3a0",
  orange        = "#ffbd5e",
  cyan          = "#ecd3a0",
  statusline_bg = "#090909",
  lightbg       = "#141414",
  pmenu_bg      = "#5ea1ff",
  folder_bg     = "#5ea1ff",
}

-- base08/05/0F collapse to fg on purpose; see polish_hl fixups
M.base_16 = {
  base00 = "#040404",
  base01 = "#090909",
  base02 = "#141414",
  base03 = "#4c4b3c",
  base04 = "#5c5a46",
  base05 = "#dcdcd4",
  base06 = "#e8e8e0",
  base07 = "#ffffff",
  base08 = "#dcdcd4",
  base09 = "#bd8c70",
  base0A = "#b5a494",
  base0B = "#bd8c70",
  base0C = "#ecd3a0",
  base0D = "#5ea1ff",
  base0E = "#ffbd5e",
  base0F = "#dcdcd4",
}

-- group overrides keyed by base46 integration name/load order
M.polish_hl = {
  defaults = {
    -- base46 puts Comment on light_grey; cyberdream dims it much further so
    -- comments stay legible against #040404 without competing with code
    Comment = { fg = "#4c4b3c", italic = true },
    Debug = { fg = "#ffbd5e" },
    Exception = { fg = "#ffbd5e" },
    -- println!/macros: soft-gold accent, pinned on every path that can
    -- resolve a macro (plain syntax, treesitter, LSP semantic tokens)
    Macro = { fg = "#ecd3a0" },
    NormalFloat = { bg = "#040404" },
    -- base46 ships MatchParen as { link = "MatchWord" }, and a deep merge
    -- cannot break an existing link -- so colour MatchWord and let
    -- MatchParen follow it
    MatchWord = { fg = "#ecd3a0", bg = "#141414" },
  },

  -- built dynamically, load after "defaults"
  statusline = {
    StatusLine = { fg = "#dcdcd4", bg = "#040404" },
    StatusLineNC = { fg = "#7b8496", bg = "#040404" },
  },

  tbline = {
    TabLine = { fg = "#7b8496", bg = "#040404" },
    TabLineFill = { fg = "#7b8496", bg = "#040404" },
    TabLineSel = { fg = "#dcdcd4", bg = "#141414", bold = false },
  },

  syntax = {
    Boolean = { fg = "#ecd3a0" },
    -- hardcoded/literal values (numbers, consts, chars) match strings:
    -- Rust's own brand orange, darkened so it does not read as bright
    Character = { fg = "#bd8c70" },
    Define = { fg = "#ecd3a0" },
    Include = { fg = "#ecd3a0" },
    -- for/in/while/loop/match/else etc. would otherwise land on Statement's
    -- colour; pin them to Keyword's orange, same as `let`/`fn`
    Label = { fg = "#ffbd5e" },
    Repeat = { fg = "#ffbd5e" },
    Operator = { fg = "#b5a494" },
    PreProc = { fg = "#ecd3a0" },
    PreCondit = { fg = "#ecd3a0" },
    SpecialChar = { fg = "#ecd3a0" },
    Statement = { fg = "#b5a494" },
    Structure = { fg = "#b5a494" },
    Tag = { fg = "#ecd3a0" },
    Todo = { fg = "#b5a494", bg = "NONE", bold = true },
    -- doc comments (///, //!, /** */) a touch brighter than plain //
    -- comments, but only slightly -- not a hard contrast jump
    SpecialComment = { fg = "#5c5a46", italic = true },
  },

  treesitter = {
    ["@variable.builtin"] = { fg = "#ecd3a0" },
    ["@character"] = { fg = "#bd8c70" },
    ["@character.special"] = { fg = "#ecd3a0" },
    ["@module"] = { fg = "#b5a494" },
    ["@namespace"] = { fg = "#ecd3a0" },
    ["@constant.macro"] = { fg = "#ecd3a0" },
    ["@function.macro"] = { fg = "#ecd3a0" },
    ["@lsp.type.macro"] = { fg = "#ecd3a0" },
    ["@keyword.exception"] = { fg = "#ffbd5e" },
    ["@keyword.repeat"] = { fg = "#ffbd5e" },
    ["@keyword.storage"] = { fg = "#ffbd5e" },
    ["@keyword.directive"] = { fg = "#ffbd5e" },
    ["@label"] = { fg = "#ffbd5e" },
    ["@tag"] = { fg = "#ffbd5e" },
    ["@attribute"] = { fg = "#ecd3a0" },
    ["@annotation"] = { fg = "#ecd3a0" },
    ["@symbol"] = { fg = "#dcdcd4" },
    ["@operator"] = { fg = "#b5a494" },
    ["@string.regex"] = { fg = "#bd8c70" },
    ["@markup.heading"] = { fg = "#dcdcd4" },
    ["@markup.raw"] = { fg = "#dcdcd4" },
    ["@markup.link"] = { fg = "#dcdcd4", underline = true },
    ["@markup.link.url"] = { fg = "#5ea1ff", underline = true },
    ["@markup.link.label"] = { fg = "#ffbd5e" },
    ["@markup.quote"] = { fg = "#4c4b3c", bg = "NONE", italic = true },
    ["@comment"] = { fg = "#4c4b3c", italic = true },
    ["@comment.documentation"] = { fg = "#5c5a46", italic = true },
    ["@comment.todo"] = { fg = "#b5a494", bg = "NONE", bold = true },
    ["@comment.warning"] = { fg = "#f1ff5e", bg = "NONE" },
    ["@comment.note"] = { fg = "#5ea1ff", bg = "NONE" },
    ["@comment.danger"] = { fg = "#4c4b3c", bg = "NONE", italic = true },
    ["@diff.delta"] = { fg = "#e6dfb8" },
  },

  lsp = {
    -- Neovim links DiagnosticUnnecessary to Comment by default, which under
    -- this palette makes unused code identical to a comment
    DiagnosticUnnecessary = { fg = "#7b8496", italic = false },
    DiagnosticInfo = { fg = "#5ea1ff" },
    DiagnosticHint = { fg = "#ecd3a0" },
    LspReferenceText = { bg = "#141414" },
    LspReferenceRead = { bg = "#141414" },
    LspReferenceWrite = { bg = "#141414" },
    -- inline "cues" (inlay hints, virtual diagnostics) as dark and muted as
    -- the rest of the palette; signs and underlines on actual errors keep
    -- full-strength colour so real problems still stand out
    LspInlayHint = { fg = "#383838", bg = "NONE", italic = true },
    DiagnosticVirtualTextError = { fg = "#604341", bg = "NONE", italic = true },
    DiagnosticVirtualTextWarn = { fg = "#544c3e", bg = "NONE", italic = true },
    DiagnosticVirtualTextInfo = { fg = "#544c44", bg = "NONE", italic = true },
    DiagnosticVirtualTextHint = { fg = "#4c4953", bg = "NONE", italic = true },
  },
}

-- diffed vs old cyberdream.nvim groups, merged into polish_hl
local ui_deltas = {
  defaults = {
    Bold = { fg = "#7b8496", bold = true, italic = true },
    CmpDocumentation = { fg = "#7b8496" },
    CmpDocumentationBorder = { fg = "#7b8496" },
    CmpGhostText = { fg = "#7b8496" },
    CmpItemAbbrDeprecated = { fg = "#7b8496", strikethrough = true },
    CmpItemAbbrMatchFuzzy = { fg = "#b5a494" },
    CmpItemKindDefault = { fg = "#7b8496" },
    ColorColumn = { bg = "#141414" },
    Comment = { fg = "#4c4b3c", italic = true },
    Conceal = { fg = "#7b8496" },
    CurSearch = { fg = "#090909", bg = "#ecd3a0" },
    CursorColumn = { bg = "#141414" },
    CursorLine = { bg = "#141414" },
    CursorLineNr = { fg = "#7b8496" },
    Debug = { fg = "#ffbd5e" },
    DiagnosticUnderlineError = { sp = "#ff6e5e", underline = false, undercurl = true },
    DiagnosticUnderlineHint = { sp = "#ecd3a0", underline = false, undercurl = true },
    DiagnosticUnderlineInfo = { sp = "#5ea1ff", underline = false, undercurl = true },
    DiagnosticUnderlineWarn = { sp = "#f1ff5e", underline = false, undercurl = true },
    DiagnosticVirtualTextError = { fg = "#604341", italic = true },
    DiagnosticVirtualTextHint = { fg = "#4c4953", italic = true },
    DiagnosticVirtualTextInfo = { fg = "#544c44", italic = true },
    DiagnosticVirtualTextWarn = { fg = "#544c3e", italic = true },
    EndOfBuffer = { fg = "#282828" },
    Error = { fg = "#ff6e5e", bg = "NONE" },
    ErrorMsg = { fg = "#ff6e5e", bg = "NONE" },
    Exception = { fg = "#ffbd5e" },
    FloatBorder = { fg = "#141414", bg = "#040404" },
    FloatTitle = { fg = "#ecd3a0", bg = "#040404" },
    FoldColumn = { fg = "#7b8496", bg = "#040404" },
    Folded = { fg = "#7b8496", bg = "#040404" },
    GitSignsAdd = { fg = "#5eff6c" },
    GitSignsAddInline = { bg = "#0c1d0d" },
    GitSignsAddLn = { bg = "#153617" },
    GitSignsChange = { fg = "#ffbd5e" },
    GitSignsChangeInline = { bg = "#0c131c" },
    GitSignsChangeLn = { bg = "#152335" },
    GitSignsCurrentLineBlame = { fg = "#282828" },
    GitSignsDelete = { fg = "#ff6e5e" },
    GitSignsDeleteInline = { bg = "#1d0e0c" },
    GitSignsDeleteLn = { bg = "#361915" },
    ICursor = { fg = "#040404", bg = "#dcdcd4" },
    IblIndent = { fg = "#0c0c0c" },
    IblScope = { fg = "#141414" },
    IncSearch = { fg = "#090909", bg = "#ecd3a0" },
    Italic = { italic = true },
    LspCodeLens = { fg = "#7b8496" },
    LspInfoBorder = { fg = "#040404" },
    Macro = { fg = "#ecd3a0" },
    ModeMsg = { fg = "#dcdcd4" },
    MoreMsg = { fg = "#5ea1ff" },
    MsgArea = { fg = "#dcdcd4" },
    NonText = { fg = "#393d45" },
    NormalFloat = { fg = "#dcdcd4", bg = "#040404" },
    NormalNC = { fg = "#dcdcd4", bg = "#040404" },
    Pmenu = { fg = "#dcdcd4", bg = "#040404" },
    PmenuMatch = { fg = "#ecd3a0", bg = "#141414", bold = false },
    PmenuMatchSel = { fg = "#ecd3a0", bg = "#141414", bold = false },
    PmenuSbar = { fg = "#040404", bg = "#141414" },
    PmenuSel = { fg = "#dcdcd4", bg = "#141414" },
    PmenuThumb = { fg = "#040404", bg = "#141414" },
    Question = { fg = "#f1ff5e" },
    QuickFixLine = { bg = "#141414" },
    Search = { fg = "#090909", bg = "#dcdcd4" },
    SignColumn = { fg = "#7b8496", bg = "#040404" },
    SignColumnSB = { fg = "#7b8496", bg = "#040404" },
    SnacksDashboardDesc = { fg = "#ecd3a0" },
    SnacksDashboardDir = { fg = "#7b8496" },
    SnacksDashboardFile = { fg = "#ecd3a0" },
    SnacksDashboardHeader = { fg = "#d0cbc0" },
    SnacksDashboardIcon = { fg = "#5ea1ff" },
    SnacksDashboardKey = { fg = "#ffbd5e" },
    SnacksDashboardNormal = { fg = "#dcdcd4", bg = "#040404" },
    SnacksDashboardSpecial = { fg = "#ecd3a0" },
    SnacksDashboardTerminal = { fg = "#dcdcd4", bg = "#040404" },
    SnacksDashboardTitle = { fg = "#dcdcd4" },
    SnacksDashoardFooter = { fg = "#ecd3a0" },
    SnacksNormal = { fg = "#dcdcd4", bg = "#040404" },
    SnacksNormalNC = { fg = "#dcdcd4", bg = "#040404" },
    SnacksNotifierBorderDebug = { fg = "#141414" },
    SnacksNotifierBorderError = { fg = "#141414" },
    SnacksNotifierBorderInfo = { fg = "#141414" },
    SnacksNotifierBorderTrace = { fg = "#141414" },
    SnacksNotifierBorderWarn = { fg = "#141414" },
    SnacksNotifierDebug = { fg = "#dcdcd4" },
    SnacksNotifierError = { fg = "#dcdcd4" },
    SnacksNotifierIconDebug = { fg = "#7b8496" },
    SnacksNotifierIconError = { fg = "#ff6e5e" },
    SnacksNotifierIconInfo = { fg = "#5ea1ff" },
    SnacksNotifierIconTrace = { fg = "#b5a494" },
    SnacksNotifierIconWarn = { fg = "#f1ff5e" },
    SnacksNotifierInfo = { fg = "#dcdcd4" },
    SnacksNotifierTitleDebug = { fg = "#7b8496" },
    SnacksNotifierTitleError = { fg = "#ff6e5e" },
    SnacksNotifierTitleInfo = { fg = "#5ea1ff" },
    SnacksNotifierTitleTrace = { fg = "#b5a494" },
    SnacksNotifierTitleWarn = { fg = "#f1ff5e" },
    SnacksNotifierTrace = { fg = "#dcdcd4" },
    SnacksNotifierWarn = { fg = "#dcdcd4" },
    SnacksPickerDir = { fg = "#7b8496" },
    SnacksPickerPrompt = { fg = "#5ea1ff", bold = true },
    SnacksPickerTotals = { fg = "#ecd3a0", bold = true },
    SnacksWinBar = { fg = "#dcdcd4" },
    SnacksWinBarNC = { fg = "#dcdcd4" },
    SpecialComment = { fg = "#5c5a46", italic = true },
    SpecialKey = { fg = "#7b8496" },
    SpellBad = { sp = "#ff6e5e", undercurl = true },
    SpellCap = { sp = "#f1ff5e", undercurl = true },
    SpellLocal = { sp = "#5ea1ff", undercurl = true },
    SpellRare = { sp = "#b5a494", undercurl = true },
    Substitute = { fg = "#ff6e5e", bg = "#141414" },
    TelescopeMultiIcon = { fg = "#dcdcd4" },
    TelescopeMultiSelection = { fg = "#b5a494" },
    TelescopePreviewBlock = { fg = "#bd8c70" },
    TelescopePreviewBorder = { fg = "#141414" },
    TelescopePreviewCharDev = { fg = "#bd8c70" },
    TelescopePreviewDate = { fg = "#5ea1ff" },
    TelescopePreviewDirectory = { fg = "#5ea1ff" },
    TelescopePreviewExecute = { fg = "#bd8c70" },
    TelescopePreviewGroup = { fg = "#bd8c70" },
    TelescopePreviewHyphen = { fg = "#393d45" },
    TelescopePreviewLine = { bg = "#141414" },
    TelescopePreviewLink = { fg = "#ecd3a0" },
    TelescopePreviewMatch = { fg = "#090909", bg = "#dcdcd4" },
    TelescopePreviewMessage = { fg = "#dcdcd4", bg = "#040404" },
    TelescopePreviewMessageFillchar = { fg = "#dcdcd4", bg = "#040404" },
    TelescopePreviewNormal = { fg = "#dcdcd4", bg = "#040404" },
    TelescopePreviewPipe = { fg = "#bd8c70" },
    TelescopePreviewRead = { fg = "#bd8c70" },
    TelescopePreviewSize = { fg = "#bd8c70" },
    TelescopePreviewSocket = { fg = "#b5a494" },
    TelescopePreviewSticky = { fg = "#ffbd5e" },
    TelescopePreviewUser = { fg = "#bd8c70" },
    TelescopePreviewWrite = { fg = "#b5a494" },
    TelescopePromptCounter = { fg = "#ecd3a0" },
    TelescopeResultsBorder = { fg = "#141414" },
    TelescopeResultsClass = { fg = "#5ea1ff" },
    TelescopeResultsComment = { fg = "#4c4b3c", italic = true },
    TelescopeResultsConstant = { fg = "#bd8c70" },
    TelescopeResultsDiffUntracked = { fg = "#393d45" },
    TelescopeResultsField = { fg = "#5ea1ff" },
    TelescopeResultsFunction = { fg = "#5ea1ff" },
    TelescopeResultsIdentifier = { fg = "#dcdcd4" },
    TelescopeResultsLineNr = { fg = "#282828" },
    TelescopeResultsNormal = { fg = "#dcdcd4", bg = "#040404" },
    TelescopeResultsNumber = { fg = "#bd8c70" },
    TelescopeResultsOperator = { fg = "#b5a494" },
    TelescopeResultsSpecialComment = { fg = "#5c5a46", italic = true },
    TelescopeResultsVariable = { fg = "#ecd3a0" },
    TelescopeSelectionCaret = { bg = "#141414" },
    TelescopeTitle = { fg = "#141414" },
    Title = { fg = "#dcdcd4" },
    VertSplit = { fg = "#141414", bg = "#040404" },
    VisualNOS = { fg = "NONE", bg = "#141414" },
    WarningMsg = { fg = "#ffbd5e" },
    WhichKeyBorder = { fg = "#141414", bg = "#040404" },
    WhichKeyFloat = { bg = "#040404" },
    WhichKeyIcon = { fg = "#5ea1ff" },
    WhichKeyIconAzure = { fg = "#e0d9c4" },
    WhichKeyIconBlue = { fg = "#5ea1ff" },
    WhichKeyIconGreen = { fg = "#5eff6c" },
    WhichKeyIconGrey = { fg = "#7b8496" },
    WhichKeyIconOrange = { fg = "#ffbd5e" },
    WhichKeyIconPurple = { fg = "#b5a494" },
    WhichKeyIconRed = { fg = "#ff6e5e" },
    WhichKeyIconYellow = { fg = "#f1ff5e" },
    WhichKeyNormal = { fg = "#dcdcd4", bg = "#040404" },
    WhichKeySeperator = { fg = "#7b8496" },
    WhichKeyTitle = { fg = "#ecd3a0", bg = "#040404" },
    WhickKeyIconCyan = { fg = "#ecd3a0" },
    Whitespace = { fg = "#141414" },
    WildMenu = { fg = "#040404", bg = "#5ea1ff" },
    WinBar = { fg = "#dcdcd4", bg = "#040404" },
    WinBarNC = { fg = "#7b8496", bg = "#040404" },
    WinSeparator = { fg = "#141414", bg = "#040404" },
    mkdCodeDelimiter = { fg = "#7b8496" },
    mkdCodeEnd = { fg = "#5ea1ff" },
    mkdCodeStart = { fg = "#5ea1ff" },
    qfFileName = { fg = "#5ea1ff" },
    qfLineNr = { fg = "#7b8496" },
  },
  syntax = {
    Boolean = { fg = "#ecd3a0" },
    Character = { fg = "#bd8c70" },
    Label = { fg = "#ffbd5e" },
    Operator = { fg = "#b5a494" },
    PreProc = { fg = "#ecd3a0" },
    Repeat = { fg = "#ffbd5e" },
    Statement = { fg = "#b5a494" },
    Todo = { fg = "#b5a494", bg = "NONE", bold = true },
  },
  treesitter = {
    ["@annotation"] = { fg = "#ecd3a0" },
    ["@attribute"] = { fg = "#ecd3a0" },
    ["@boolean"] = { fg = "#ecd3a0" },
    ["@character"] = { fg = "#bd8c70" },
    ["@character.special"] = { fg = "#ecd3a0" },
    ["@comment"] = { fg = "#4c4b3c", italic = true },
    ["@comment.documentation"] = { fg = "#5c5a46", italic = true },
    ["@constant.builtin"] = { fg = "#ecd3a0" },
    ["@constant.macro"] = { fg = "#ecd3a0" },
    ["@function.macro"] = { fg = "#ecd3a0" },
    ["@keyword.coroutine"] = { fg = "#ffbd5e" },
    ["@keyword.exception"] = { fg = "#ffbd5e" },
    ["@keyword.operator"] = { fg = "#b5a494" },
    ["@keyword.repeat"] = { fg = "#ffbd5e" },
    -- definitions get green, control flow stays orange
    ["@keyword.function"] = { fg = "#5eff6c", bold = true },
    ["@keyword.type"] = { fg = "#5eff6c", bold = true },
    ["@label"] = { fg = "#ffbd5e" },
    ["@markup.heading.1"] = { fg = "#ffbd5e", bold = true },
    ["@markup.heading.2"] = { fg = "#ecd3a0", bold = true },
    ["@markup.heading.3"] = { fg = "#5ea1ff", bold = true },
    ["@markup.heading.4"] = { fg = "#b5a494", bold = true },
    ["@markup.heading.5"] = { fg = "#b5a494", bold = true },
    ["@markup.heading.6"] = { fg = "#5eff6c", bold = true },
    ["@markup.italic"] = { fg = "#5ea1ff", italic = true },
    ["@markup.link.label"] = { fg = "#ffbd5e" },
    ["@markup.link.label.markdown_inline"] = { fg = "#ecd3a0" },
    ["@markup.link.markdown_inline"] = { fg = "#5ea1ff" },
    ["@markup.link.url"] = { fg = "#5ea1ff", underline = true },
    ["@markup.list.checked"] = { fg = "#5eff6c", bold = true },
    ["@markup.list.unchecked"] = { fg = "#b5a494", bold = true },
    ["@markup.quote"] = { fg = "#4c4b3c", bg = "NONE", italic = true },
    ["@markup.strong"] = { fg = "#ecd3a0", bold = true },
    ["@method"] = { fg = "#5ea1ff" },
    ["@method.call"] = { fg = "#5ea1ff" },
    ["@module"] = { fg = "#b5a494" },
    ["@namespace"] = { fg = "#ecd3a0" },
    ["@operator"] = { fg = "#b5a494" },
    ["@punctuation.special"] = { fg = "#dcdcd4" },
    ["@string.documentation"] = { fg = "#4c4b3c", italic = true },
    ["@string.regex"] = { fg = "#bd8c70" },
    ["@string.special"] = { fg = "#ecd3a0" },
    ["@symbol"] = { fg = "#dcdcd4" },
    ["@tag"] = { fg = "#ffbd5e" },
    ["@type.builtin"] = { fg = "#c8b498" },
    ["@type.definition"] = { fg = "#b5a494" },
    ["@type.qualifier"] = { fg = "#ffbd5e" },
    ["@variable.builtin"] = { fg = "#ecd3a0" },
  },
  lsp = {
    DiagnosticHint = { fg = "#ecd3a0" },
    DiagnosticInfo = { fg = "#5ea1ff" },
    LspInlayHint = { fg = "#383838", bg = "NONE", italic = true },
    LspReferenceRead = { bg = "#141414" },
    LspReferenceText = { bg = "#141414" },
    LspReferenceWrite = { bg = "#141414" },
    LspSignatureActiveParameter = { fg = "#ffbd5e", bg = "NONE" },
  },
  git = {
    DiffAdd = { fg = "NONE", bg = "#153617" },
    DiffChange = { fg = "NONE", bg = "#152335" },
    DiffDelete = { fg = "NONE", bg = "#361915" },
    DiffText = { fg = "NONE", bg = "#362815" },
  },
  telescope = {
    TelescopeBorder = { fg = "#141414", bg = "NONE" },
    TelescopeMatching = { fg = "#ecd3a0", bg = "NONE" },
    TelescopeNormal = { fg = "#dcdcd4", bg = "#040404" },
    TelescopePreviewTitle = { fg = "#b5a494", bg = "NONE" },
    TelescopePromptBorder = { fg = "#141414", bg = "NONE" },
    TelescopePromptNormal = { fg = "#dcdcd4", bg = "#040404" },
    TelescopePromptPrefix = { fg = "#ecd3a0", bg = "NONE" },
    TelescopePromptTitle = { fg = "#5ea1ff", bg = "NONE" },
    TelescopeResultsDiffAdd = { fg = "NONE", bg = "#153617" },
    TelescopeResultsDiffChange = { fg = "NONE", bg = "#152335" },
    TelescopeResultsDiffDelete = { fg = "NONE", bg = "#361915" },
    TelescopeResultsTitle = { fg = "#ecd3a0", bg = "NONE" },
    TelescopeSelection = { fg = "NONE", bg = "#141414" },
  },
  cmp = {
    CmpItemAbbrMatch = { fg = "#b5a494", bold = false },
    CmpItemKindFunction = { fg = "#ecd3a0" },
    CmpItemKindInterface = { fg = "#ecd3a0" },
    CmpItemKindKeyword = { fg = "#dcdcd4" },
    CmpItemKindMethod = { fg = "#ecd3a0" },
    CmpItemKindText = { fg = "#ecd3a0" },
    CmpItemKindUnit = { fg = "#dcdcd4" },
    CmpItemKindVariable = { fg = "#ecd3a0" },
    CmpItemMenu = { fg = "#7b8496" },
  },
  whichkey = {
    WhichKey = { fg = "#ecd3a0" },
    WhichKeyDesc = { fg = "#ecd3a0" },
    WhichKeyGroup = { fg = "#5ea1ff" },
    WhichKeyValue = { fg = "#5ea1ff" },
  },
}

-- readability pass, applied last, wins over tables above
-- IblChar/IblScopeChar are the real indent-guide groups
local readability = {
  defaults = {
    LineNr = { fg = "#535353" },       -- gutter digits, was #282828
    CursorLineNr = { fg = "#bdbdbd" }, -- digit on the cursor line, was #7b8496
    Whitespace = { fg = "#2f2f2f" },   -- listchars, was #141414
    IblIndent = { fg = "#2f2f2f" },
    IblScope = { fg = "#565656" },
  },

  blankline = {
    IblChar = { fg = "#2f2f2f" },      -- indent guide, was #141414
    IblScopeChar = { fg = "#565656" }, -- current-scope guide, was #282828
  },
}

M.polish_hl = require("base46").merge_tb(M.polish_hl, ui_deltas)
M.polish_hl = require("base46").merge_tb(M.polish_hl, readability)

M.type = "dark"

M = require("base46").override_theme(M, "cyberdream_custom")

return M
